server:
  port:
    7000
  servlet:
    encoding:
      charset: UTF-8
#  tomcat:
#    threads:
#      min-spare: 10
#      max: 20
#
logging:
  level:
#    com.zaxxer.hikari.HikariConfig: DEBUG
#    com.zaxxer.hikari: TRACE
    com.risingtest.wanted: INFO

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  devtools:
    livereload:
      enabled: true
  activate:
    on-profile:
      - local

  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/wanted_clone
    username: root
    password: root
#    driver-class-name: org.mysql.jdbc.Driver
    hikari:
      idle-timeout: 28799000
      max-lifetime: 28799000
      leak-detection-threshold: 2000
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql : true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  jackson:
    property-naming-strategy: SNAKE_CASE

  jwt:
    secret-key: SECRET_KEY

app:
  upload:
    dir : C://wanted//images
    separator : //
