server:
  port:
    7000
#  tomcat:
#    threads:
#      min-spare: 10
#      max: 20
#
#logging:
#  level:
#    com.zaxxer.hikari.HikariConfig: DEBUG
#    com.zaxxer.hikari: TRACE
#    com.risingtest.wanted.src.user: INFO

spring:
  devtools:
    livereload:
      enabled: true
  activate:
    on-profile:
      - local
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/wanted_clone
    username: root
    password: root
#    driver-class-name: org.mysql.jdbc.Driver
    hikari:
      idle-timeout: 28799970
      leak-detection-threshold: 2000
      max-lifetime: 28799970
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql : true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  jackson:
    property-naming-strategy: SNAKE_CASE

  jwt:
    secret-key: SECRET_KEY

app:
  upload:
    #dir : /home/ubuntu/images/users
    dir : C://wanted//images
